config/routes.rb
Rails.application.routes.draw do
  resources :members
  root 'groups#index'
  get 'groups/index'
  get 'groups', to: 'groups#new', as: 'group_new'
  post 'groups', to: "groups#create"
  get 'groups/:id', to: 'groups#show', as: 'group'
  get 'groups/:id/edit', to: 'groups#edit', as: 'group_edit'
  patch 'groups/:id', to: 'groups#update'
  delete 'groups/:id', to: 'groups#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    enum status: ["Activo", "No activo", "Retirado"]
    before_save :fuera_chadwick
    has_many :members, dependent: :destroy

    def fuera_chadwick
        self.name = self.name.gsub("Chadwick", "Hola")
        # self.name = self.name.split.reduce([]) {|name, value| name.push(value) if value != "Chadwick"; name}.join("")
    end

    def to_s
        name
    end
    

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  validates :name, presence: true

  def to_s
    name
  end
  
end

app/controllers/api/v1/groups_controller.rb
module Api
  module V1
    class GroupsController < V1Controller
      before_action :set_group, only: %i[show edit update destroy]
      before_action :set_statuses, only: %i[edit new]
      # http_basic_authenticate_with name: "G44", password: "123456", only: :new
      def todos
        @groups = Group.all
        render json: @groups
      end
      
      def index
        if params[:q]
          @groups = Group.where('name LIKE ?', "%#{params[:q]}%")
          if @groups.nil?
            @groups = Group.all
          end
        else
          @groups = Group.all
        end
      end

      def new
        @group = Group.new
      end

      def create
        @group = Group.new(group_params)

        if @group.save
          redirect_to root_path
        else
          render :new
        end

        # respond_to do |format|
        #   if @group.save
        #     format.html { redirect_to root_path, notice: "La re creaste jeje saludos" }
        #   else
        #     format.html { render :new }
        #   end
        # end

      end

      def show
      end
      
      def edit
      end
      
      def update
        if @group.update(group_params)
          redirect_to @group
        else
          render :edit
        end
      end
      
      def destroy
        @group.destroy
        redirect_to root_path
      end
      

      private

      def set_statuses
        @statuses = Group.statuses.keys
      end
      

      def set_group
        @group = Group.find(params[:id])
      end
      

      def group_params
        params.require(:group).permit(:name, :members, :email, :nick_name, :phone, :status)
      end
      
    end
  end
end

app/controllers/api/v1_controller.rb
module Api
    class V1Controller < ApplicationController
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]
  before_action :set_groups, only: [:new, :edit, :create, :update]
  
  # GET /members or /members.json
  def index
    # @members = Member.includes(:group)
    @members = Member.eager_load(:group)
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
    # @groups = Group.pluck :name, :id esta es para el segundo comentario
  end

  # GET /members/1/edit
  def edit
    # @groups = Group.pluck :name, :id
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_groups
      @groups = Group.all
    end
    

    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :age, :group_id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/groups/edit.html.erb
<%= render 'shared/form' %>

app/views/groups/index.html.erb
<h1 class="text-center">Grupos</h1>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Miembros</th>
            <th scope="col">Email</th>
            <th scope="col">Nicks</th>
            <th scope="col">Telefono</th>
            <th scope="col">Estado</th>
            <th colspan="3">Botones</th>
        </tr>
    </thead>
    <tbody>
        <% @groups.each do |group|%>
            <tr scope="row">
                <td><%= group.id %></td>
                <td><%= group.name %></td>
                <td>
                    <% group.members.each do |m| %>
                        <%= m %><br>
                    <% end %>
                </td>
                <td><%= group.email %></td>
                <td><%= group.nick_name %></td>
                <td><%= group.phone %></td>
                <td><%= group.status %></td>
                <td><%= link_to "Ver Grupo", group_path(group), class: 'btn btn-success' %></td>
                <td><%= link_to "Editar Grupo", group_edit_path(group.id), class: 'btn btn-warning' %></td>
                <td><%= link_to "Eliminar Grupo", group ,method: :delete, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Crear Nuevo Grupo" , group_new_path, class: 'btn btn-primary'%>

app/views/groups/new.html.erb
<%= render 'shared/form' %>

app/views/groups/show.html.erb
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @group.id %></li>
        <li class="list-group-item"><%= @group.name %></li>
        <li class="list-group-item"><%= @group.members %></li>
        <li class="list-group-item"><%= @group.email %></li>
        <li class="list-group-item"><%= @group.nick_name %></li>
        <li class="list-group-item"><%= @group.phone %></li>
        <li class="list-group-item"><%= @group.status %></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grupos</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container pt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :member_age %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%# <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
    <%# <%= form.select :group_id, options_for_select(@groups) %>
    <%= form.collection_select :group_id, @groups, :id, :name%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.age %></td>
        <td><%= member.group %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @member.age %>
</p>

<p>
  <strong>Group:</strong>
  <%= @member.group %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/shared/_form.html.erb
<%= form_with(model: @group, local: true) do |f| %>

    <div class="form-group">
        <%= f.label :name %> 
        <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="form-group">
        <%= f.label :members, "Miembros" %> 
        <%= f.number_field :members, placeholder: 'Miembros', class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email %> 
        <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :nick_name %> 
        <%= f.text_field :nick_name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :phone %> 
        <%= f.telephone_field :phone, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :status %>
        <%= f.select :status, options_for_select(@statuses) %>
    </div>

    <hr>

    <%= f.submit "Enviar", class: 'btn btn-primary' %>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <!-- <form class="form-inline">
    <input class="form-control ml-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form> -->

    <%= form_tag groups_index_path, method: :get do %>
        <%= text_field_tag :q, nil, class: 'btn btn-outline-success my-2 my-sm-0'%>
        <%= submit_tag "Buscar", class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
</nav>